from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from core import views

urlpatterns = [
    path("health/", views.HealthView.as_view(), name="health"),
    path("auth/login/", views.LoginView.as_view(), name="login"),
    path("auth/register/", views.StudentRegisterView.as_view(), name="register"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("auth/password-reset/", views.PasswordResetRequestView.as_view(), name="password-reset"),
    path("auth/password-reset/confirm/", views.PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("auth/me/", views.MeView.as_view(), name="me"),
    path("auth/change-password/", views.ChangePasswordView.as_view(), name="change-password"),
    path("complaints/", views.ComplaintListCreateView.as_view(), name="complaint-list"),
    path("complaints/track/", views.ComplaintTrackView.as_view(), name="complaint-track"),
    path("complaints/<str:tracking_id>/", views.ComplaintDetailView.as_view(), name="complaint-detail"),
    path("suggestions/", views.SuggestionListCreateView.as_view(), name="suggestion-list"),
    path("suggestions/<int:pk>/", views.SuggestionDetailView.as_view(), name="suggestion-detail"),
    path("clubs/", views.ClubListView.as_view(), name="club-list"),
    path("clubs/<int:pk>/join/", views.ClubJoinView.as_view(), name="club-join"),
    path("events/", views.EventListView.as_view(), name="event-list"),
    path("events/<int:pk>/register/", views.EventRegisterView.as_view(), name="event-register"),
    path("news/", views.NewsListView.as_view(), name="news-list"),
    path("documents/", views.DocumentListView.as_view(), name="document-list"),
    path("contact/", views.ContactCreateView.as_view(), name="contact"),
    path("stats/executive/", views.ExecutiveStatsView.as_view(), name="executive-stats"),
    path("stats/transparency/", views.TransparencyStatsView.as_view(), name="transparency-stats"),
    path("admin/users/", views.AdminUsersView.as_view(), name="admin-users"),
    path("admin/users/<path:reg_number>/", views.AdminUserUpdateView.as_view(), name="admin-user-update"),
    path("admin/staff/", views.AdminStaffCreateView.as_view(), name="admin-staff-create"),
    path("admin/ministries/", views.MinistryListView.as_view(), name="ministry-list"),
    path("admin/documents/", views.AdminDocumentCreateView.as_view(), name="admin-document-create"),
    path("admin/documents/<int:pk>/", views.AdminDocumentDetailView.as_view(), name="admin-document-detail"),
    path("admin/news/", views.AdminNewsCreateView.as_view(), name="admin-news-create"),
    path("admin/news/<int:pk>/", views.AdminNewsDetailView.as_view(), name="admin-news-detail"),
    path("admin/contact-messages/", views.AdminContactMessageListView.as_view(), name="admin-contact-messages"),
    path("admin/clubs/", views.AdminClubCreateView.as_view(), name="admin-club-create"),
    path("admin/clubs/<int:pk>/", views.AdminClubDetailView.as_view(), name="admin-club-detail"),
    path("admin/events/", views.AdminEventCreateView.as_view(), name="admin-event-create"),
    path("admin/events/<int:pk>/", views.AdminEventDetailView.as_view(), name="admin-event-detail"),
    path("admin/backup/", views.AdminBackupView.as_view(), name="admin-backup"),
    path("admin/system-status/", views.AdminSystemStatusView.as_view(), name="admin-system-status"),
    path("admin/overview/", views.AdminOverviewView.as_view(), name="admin-overview"),
]
